name: Flutter Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Forzamos a que todas las acciones usen Node 24 como indica el blog de GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Nota: Usamos la versión estable más reciente para evitar conflictos de linter
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Paso crítico: Crear el .env para que flutter_dotenv no lance error en el test
      - name: Create .env file
        run: touch .env

      - name: Analyze project
        # Usamos --fatal-infos para que el análisis sea riguroso como pide la rúbrica
        run: flutter analyze

      - name: Run tests
        run: flutter test